apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: salary
  name: salary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salary
  template:
    metadata:
      labels:
        app: salary
    spec:
      containers:
      - image: shubhamk0/salary:1
        name: salary-container
        ports:
        - containerPort: 8080
        env:
        - name: SALARY_SCYLLADB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: "salary-configmap"
              key: "salary-scylladb-username"
        - name: SCYLLADB_URL
          valueFrom:
            configMapKeyRef:
              name: "salary-configmap"
              key: "scylladb-url"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: "salary-configmap"
              key: "redis-url"
        - name: SALARY_SCYLLADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "salary-secret"
              key: "salary-scylladb-password"
        - name: SALARY_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "salary-secret"
              key: "salary-redis-password"