apiVersion: v1
kind: Service
metadata:
  labels:
    app: scylladb
  name: scylladb-svc
  namespace: default
spec:
  ports:
  - name: scylladb-port
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: scylladb
  type: NodePort
