apiVersion: v1
kind: Secret
metadata:
  name: {{ include "salary-api-helm.name" . }}-secret
type: Opaque
data:
  scylladb-password: {{ .Values.scylladbPassword }}
  redis-password:  {{ .Values.redisPassword }}
