apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "salary-api-helm.name" . }}-configmap
  labels:
    app: salary
data:
  redis-url: {{ .Values.redisUrl }}
  scylladb-url: {{ .Values.scylladbUrl }}
  salary-scylladb-username: {{ .Values.scylladbUsername }}
