apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-api-helm.name" . }}-deployement
  labels:
    {{- include "employee-api-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "employee-api-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "employee-api-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 25
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: EMPLOYEE_SCYLLADB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: "{{ include "employee-api-helm.name" . }}-configmap"
                key: "employee-scylladb-username"
          - name: SCYLLADB_URL
            valueFrom:
              configMapKeyRef:
                name: "{{ include "employee-api-helm.name" . }}-configmap"
                key: "scylladb-url"
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: "{{ include "employee-api-helm.name" . }}-configmap"
                key: "redis-url"
          - name: EMPLOYEE_SCYLLADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ include "employee-api-helm.name" . }}-secret"
                key: "employee-scylladb-password"
          - name: EMPLOYEE_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "employee-secret"
                key: "employee-redis-password"