apiVersion: v1
kind: Secret
metadata:
  name: {{ include "employee-api-helm.name" . }}-secret
type: Opaque
data:
  employee-scylladb-password: {{ .Values.employeePassword }}
  employee-redis-password:  {{ .Values.employeeRedisPassword }}
