apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "employee-api-helm.name" . }}-configmap
  labels:
    app: employee
data:
  redis-url: {{ .Values.redisUrl }}
  scylladb-url: {{ .Values.scylladbUrl }}
  employee-scylladb-username: {{ .Values.employeeUsername }}
