apiVersion: v1
kind: Service
metadata:
  name: {{ include "employee-api-helm.name" . }}-svc
  labels:
    {{- include "employee-api-helm.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "employee-api-helm.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP