apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-svc
  namespace: default
spec:
  ports:
  - name: frontendport
    nodePort: 32647
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
  type: NodePort
